namespace: at41457-uat-recsdiui-uat
resources:
  - ../base
images:
  - name: myregistry.azurecr.io/react-ui
    newTag: uat-latest
patches:
  - target:
      kind: Ingress
      name: react-ui-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: reactui-uat.mycompany.com
